name: enable-rdp

on:
  workflow_dispatch:

jobs:
  build:
    name: Enable RDP and Start Session
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          net localgroup "Remote Desktop Users" "YourUsername" /add
